### ISSUE TITLE
add BLUFORCE Tracking

### ISSUE THREAD

**Issue by ghost** [GermanCoopCommunity/GeCoTemplate#1]
- [ ] Add map marker with group name for each group leader.
- [ ] Default Marker should be the be the blufor marker without any unit specification.
- [ ] Add opportunity to change marker to specify to the group type. I think setVariable to the group is a good way. Define the hook point to do the specialization in a settings file or init.
- [ ] Delete the marker if all group member left the game.
- [ ] Add marker if new group join the game.
